version: "3.9"
services:
  frontend:
    container_name: nuxtjs_output_with_crud_frontend
    build: ./
    tty: true
    ports:
      - 80:3000
    volumes:
      - ./:/frontend
      - /etc/localtime:/etc/localtime:ro # タイムゾーンを日本時刻に設定
    environment:
      TZ: Asia/Tokyo # タイムゾーンを日本時刻に設定
    security_opt:
      - seccomp:unconfined
    command: sh -c 'npm install && npm run dev'
